// actions
const SET_TODOS = 'SET_TODOS';
const UNDO_SET_TASKS_DONE = 'UNDO_SET_TASKS_DONE';
const SET_TASKS_DONE = 'SET_TASKS_DONE';
const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
const REMOVE_ITEM = 'REMOVE_ITEM';
const REINIT_DATA = 'REINIT_DATA';

export {
  SET_TODOS,
  SET_TASKS_DONE,
  SET_CURRENT_TASK,
  UNDO_SET_TASKS_DONE,
  REMOVE_ITEM,
  REINIT_DATA,
};
