const ROUTES = {
  SPLASH_SCREEN: 'SplashScreen',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  AUTH_SCREEN: 'AuthScreen',
  HOME_SCREEN: 'HomeScreen',
  DRAWER: 'DrawerNavigator',
  TAB: 'TabNavigator',
  WISHLIST: 'WishListScreen',
  PROFILE: 'ProfileScreen',
  HISTORY: 'HistoryScreen',
  SEARCH_SCREEN: 'SearchScreen',
  PRODUCT_DETAIL_SCREEN: 'ProductDetailScreen',
  CART_SCREEN: 'CartScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  CONNECTION_CHECKER_SCREEN: 'ConnectionCheckerScreen',
  CHANGE_INFORMATION: 'ChangeInformationScreen',
  CAMERA: 'CameraScreen',
  CODE_SCANNER: 'CodeScannerScreen',
  RENDER_HTML: 'RenderHTMLScreen',
  WEB_VIEW: 'WebViewScreen',
  GEOLOCATION: 'GeoLocationScreen',
};
export { ROUTES };
