#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Avoid commit to release branches
branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" =~ "release" ]]; then
  echo "You can't commit directly to release branch"
  exit 1
fi

# Linting
yarn lint-staged
